config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'documents/index'

  get 'documents/show'

  resources :iter_extracts do
    collection { post :import }
    resources :documents, only: [:index, :show]
  end

  root to: "static_pages#home"

  authenticate :user do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/iter_extract.rb
class IterExtract < ActiveRecord::Base
  has_many :documents, dependent: :destroy
  accepts_nested_attributes_for :documents

  validates_associated :documents

  def self.import(file)
    new_import = IterExtract.create!
    CSV.foreach(file.path, headers: true) do |row|
      row = row.to_hash
      # {"Reference"=>"PE573.128" or "A8-0057/2015"
      doc_reference = row["Reference"]
      pe_ref = false
      ax_ref = false
      if /PE\d{3}.\d{3}/.match doc_reference
        pe_ref = doc_reference
      elsif /A\d-\d{4}\/\d{4}/.match doc_reference
        ax_ref = doc_reference
      end
      # "Contribution"=>nil,
      contribution = row["Contribution"]
      # "Version"=>"v01-00",
      version = row["Version"][2].to_i
      # "Title"=>"European Commission: Consolidated annual accounts of the European Union - Financial Year 2014 - European Environment Agency (EEA)",
      title = row["Title"]
      # "Family"=>"AME - Amendment",
      family = row["Family"]
      # "Type"=>"AMCO (AM) - Amendments in committee to draft report or opinion",
      doc_type = row["Type"][6..7]
      # "Original language"=>"en",
      language = row["Original language"].upcase
      # "Status"=>"Ended",
      status = row["Status"].downcase
      # "Originating institution"=>"PE - European Parliament",
      source_institution = row["Originating institution"]
      # "Organ"=>"ENVI - Environment, Public Health and Food Safety",
      committee = row["Organ"][0..3]
      # "FDR Number"=>"1081326",
      fdr = row["FDR Number"]
      # "FDR Status"=>"Workflow finished",
      fdr_status = row["FDR Status"]
      # "Document date"=>"22/12/2015",
      translation_submission_date = row["Document date"].to_date if row["Document date"].size == 10

      # "Registered"=>"09/12/2015",
      iter_creation_date = row["Registered"].to_date if row["Registered"].size == 10
      # "KEY_FDRNUMBER"=>"1081326",
      rules = row["Rules"]
      # "Rules"=>nil}

      unless status == "in preparation" || family == "DEP - Tabled text"#don't import files with "in preparation"
        #binding.pry
        new_import.documents.where(pe_num: pe_ref, doc_type: doc_type).first_or_initialize do |doc|
          if doc.no_versions && doc.no_versions < version
            doc.no_versions = version
          else
            doc.no_versions = version
          end
          doc.doc_lang = language
          doc.committee = committee
          doc.title = title
          doc.iter_creation = iter_creation_date
          doc.translation_submission = translation_submission_date
          doc.save
          FetchDocumentDataJob.perform_later doc.id
        end
      end
    end
  end

end

app/controllers/iter_extracts_controller.rb
class IterExtractsController < ApplicationController

  def index
    @iter_extracts = IterExtract.all.order(:created_at)
  end

  def import
    IterExtract.import(params[:file])
    redirect_to iter_extracts_url, notice: 'ITER Extract Successfully Imported.
                                           Documents are now being processed - it will take a few minutes.'
  end

  def destroy

  end
end

app/helpers/iter_extracts_helper.rb
module IterExtractsHelper
  def time_range(iter_extract_id)
    single_extract = IterExtract.find(iter_extract_id)
    unless single_extract.documents.empty?
      months = single_extract.documents.group_by_month(:translation_submission).count.map { |k,v| k }
      start_date = months.first.to_formatted_s(:short_month_and_year)
      end_date = months.last.to_formatted_s(:short_month_and_year)
      return "#{start_date} - #{end_date}"
    end
    "No documents"
  end

  def error_count(iterextract)
    err_procedure = iterextract.documents.where(procedure: "ERROR").count
    err_template = iterextract.documents.where(template_name: "ERROR").count
    err_ulrs = iterextract.documents.where(oeil_ok: false).where(reg_ok: false).count
    err_procedure + err_template + err_ulrs
  end
end

app/views/iter_extracts/_iter_extract.html.erb
<tr>
  <td><%= iter_extract.created_at.to_formatted_s(:short) %></td>
  <td><%= time_range(iter_extract.id) %></td>
  <td><%= iter_extract.documents.try(:first).try(:doc_type) %></td>
  <td><%= iter_extract.documents.count %></td>
  <td><%= error_count(iter_extract) %></td>
  <td class="collapsing">
    <%= link_to iter_extract_documents_url(iter_extract), class: 'ui small blue button' do %>
      <i class="bar chart icon"></i> Open
    <% end %>
    <%= link_to iter_extract_path(iter_extract), method: :delete, class: 'ui small button' do %>
      <i class="delete icon"></i> Delete (to-do)
    <% end %>
  </td>
</tr>

app/views/iter_extracts/index.html.erb
<%= provide(:title, 'All ITER Extracts') %>

<div class="ui basic segment">
  <h2 class="ui header dash_header">
    <i class="lab icon"></i>
    <div class="content">
      ITER Extracts
    </div>
  </h2>
  <p>List of uploaded Iter Extracts - each line in the table represents a separate upload.</p>
  <table class="ui padded selectable celled table">
    <thead>
      <tr>
        <th>Upload Date</th>
        <th>Time Range</th>
        <th>Doc Type</th>
        <th>Document Count</th>
        <th>Issues</th>
        <th>Link</th>
      </tr>
    </thead>
    <tbody>
    <% @iter_extracts.each do |iter_extract| %>
      <%= render iter_extract %>
    <% end %>
    </tbody>
  </table>
</div>