config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'documents/index'

  get 'documents/show'

  resources :iter_extracts do
    collection { post :import }
    resources :documents, only: [:index, :show]
  end

  root to: "static_pages#home"

  authenticate :user do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= giveFullPageTitle(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
<% if user_signed_in? %>
<div class="ui inverted huge fixed menu">
  <div class="ui container">
    <a href="<%= root_path %>" class="header <% if params[:controller] == 'static_pages' && params[:action] == 'home' %> active <% end %> item">
      Home
    </a>
    <a href="<%= documents_index_path %>" class="item <% if params[:controller] == 'documents' && !params[:iter_extract_id] %> active <% end %>">
      <i class="load_ready bar chart icon"></i>
      Documents
      <div class="ui <% if params[:controller] == 'documents' && !params[:iter_extract_id] %> red <% else %> grey <% end %> label"><%= Document.all.count %></div>
    </a>
    <a href="<%= iter_extracts_path %>" class="iter <% if params[:controller] == 'iter_extracts' || params[:iter_extract_id] %> active <% end %> item">
      <i class="load_ready lab icon"></i>
      Iter Extracts
      <div class="ui <% if params[:controller] == 'iter_extracts' || params[:iter_extract_id] %> red <% else %> grey <% end %> label"><%= IterExtract.all.count %></div>
      <i class="dropdown icon"></i>
    </a>
    <div class="right menu">
    <a href="<%= static_pages_help_path %>" class="header <% if params[:controller] == 'static_pages' && params[:action] == 'help' %> active <% end %> item">
      Help
      </a>
      <%= link_to "Logout", destroy_user_session_path, class: 'ui item', method: "DELETE" %>
    </div>
  </div>
</div>
<% end %>

<div class="ui main container">
  <%= render 'shared/flashes' %>
  <%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>

<% if user_signed_in? %>
    <div class="ui upload small modal">
      <div class="header">
        Upload a New CVS ITER File
      </div>
      <div class="ui basic segment">
        <%= form_tag({action: :import, controller: :iter_extracts}, multipart: true) do %>
            <div class="ui left icon input">
              <%= file_field_tag "file", accept: 'text/csv' %>
              <i class="file icon"></i>
            </div>
            <%= submit_tag "Upload CSV", class: "ui primary button" %>
        <% end %>
      </div>
      <div class="actions">
        <div class="ui close button">Close</div>
      </div>
    </div>

   <!-- Menu Popup -->
    <div class="ui flowing basic extract popup">
      <div class="ui two column relaxed divided grid">
        <div class="column ">
          <h4 class="ui header">Existing ITER Uploads</h4>
          <div class="ui link list extract_list">
            <% IterExtract.includes(:documents).order('documents.doc_type').each do |extract| %>
                <%= link_to iter_extract_documents_path(extract), class: 'item single_extract_line' do %>

                      <% if extract.documents.first.doc_type == 'PR' %>
                        <div class="ui yellow empty circular label"></div>
                    <% elsif extract.documents.first.doc_type == 'PA' %>
                        <div class="ui olive empty circular label"></div>
                    <% elsif extract.documents.first.doc_type == 'AM' %>
                        <div class="ui green empty circular label"></div>
                    <% else %>
                        <div class="ui yellow empty circular label"></div>
                    <% end %>
                      <%= "#{time_range(extract.id)} - #{extract.documents.count} - Type: #{extract.documents.first.doc_type}" %>
                    <div class='right floated content'>
                      <i class='load_ready spinner loading icon' style="display: none"></i>
                    </div>
                <% end %>
          <% end %>
          </div>
        </div>
        <div class="center aligned column container segment">
          <h4 class="ui header">Missing data?</h4>
          <button class="ui upload button"><i class="cloud upload icon"></i>Upload New ITER CSV</button>
        </div>
      </div>
    </div>
<% end %>
</body>
</html>